services:
  api-gateway:
    image: wecare-api-gateway
    container_name: wecare-api-gateway
    restart: always
    entrypoint: []
    command: sh -c "node /app/dist/apps/api-gateway/main.js"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://linkupp:Linkupp2024!@pgm-gs5p081lmu5uty2qio.pgsql.singapore.rds.aliyuncs.com:5432/wecare?schema=public
      - DATABASE_RETRY_ATTEMPTS=5
      - DATABASE_RETRY_DELAY=5000
      - JWT_SECRET=WECARE_$2b$10$52yMT.v7Py/TxUIHiG5X7OT9xbDU8imZ0VDwNWBaHidinJ/aNKme2
      - SHIFT_SERVICE_HOST=shift-service
      - VISIT_SERVICE_HOST=visit-service
      - PORT=4200
    ports:
      - "4200:4200"
    networks:
      - wecare-network

  shift-service:
    image: wecare-shift-service
    container_name: wecare-shift-service
    restart: always
    entrypoint: []
    command: sh -c "node /app/dist/apps/shift/main.js"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://linkupp:Linkupp2024!@pgm-gs5p081lmu5uty2qio.pgsql.singapore.rds.aliyuncs.com:5432/wecare?schema=public
      - DATABASE_RETRY_ATTEMPTS=5
      - DATABASE_RETRY_DELAY=5000
      - JWT_SECRET=WECARE_$2b$10$52yMT.v7Py/TxUIHiG5X7OT9xbDU8imZ0VDwNWBaHidinJ/aNKme2
      - PORT=4201
      - SHIFT=0.0.0.0
      - HOST=0.0.0.0
    ports:
      - "4201:4201"
    networks:
      - wecare-network

  visit-service:
    image: wecare-visit-service
    container_name: wecare-visit-service
    restart: always
    entrypoint: []
    command: sh -c "node /app/dist/apps/visit/main.js"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://linkupp:Linkupp2024!@pgm-gs5p081lmu5uty2qio.pgsql.singapore.rds.aliyuncs.com:5432/wecare?schema=public
      - DATABASE_RETRY_ATTEMPTS=5
      - DATABASE_RETRY_DELAY=5000
      - JWT_SECRET=WECARE_$2b$10$52yMT.v7Py/TxUIHiG5X7OT9xbDU8imZ0VDwNWBaHidinJ/aNKme2
      - PORT=4202
      - VISIT=0.0.0.0
      - HOST=0.0.0.0
    ports:
      - "4202:4202"
    networks:
      - wecare-network

  frontend:
    image: wecare-frontend
    container_name: wecare-frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://8.219.89.94:4200
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - wecare-network

networks:
  wecare-network:
    driver: bridge
