version: "3.8"

services:
  db:
    image: postgres:15
    container_name: wecare-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wecare
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wecare-network

  api-gateway:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      args:
        - APP_NAME=api-gateway
    container_name: wecare-api-gateway
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/wecare
      - JWT_SECRET=WECARE_$2b$10$52yMT.v7Py/TxUIHiG5X7OT9xbDU8imZ0VDwNWBaHidinJ/aNKme2
      - SHIFT_SERVICE_HOST=shift-service
      - VISIT_SERVICE_HOST=visit-service
    ports:
      - "4200:4200"
    depends_on:
      - db
    networks:
      - wecare-network

  shift-service:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      args:
        - APP_NAME=shift
    container_name: wecare-shift-service
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/wecare
    ports:
      - "4201:4201"
    depends_on:
      - db
    networks:
      - wecare-network

  visit-service:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      args:
        - APP_NAME=visit
    container_name: wecare-visit-service
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/wecare
    ports:
      - "4202:4202"
    depends_on:
      - db
    networks:
      - wecare-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: wecare-frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4200
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - wecare-network

networks:
  wecare-network:
    driver: bridge

volumes:
  postgres_data:
